# Generated by Django 5.1.4 on 2024-12-20 13:26

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('image', models.ImageField(blank=True, upload_to=main.models.category_photo_path, verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание изготовителя')),
                ('image', models.ImageField(blank=True, upload_to=main.models.producer_photo_path, verbose_name='Изображение компании')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата регистрации на сайте')),
            ],
            options={
                'verbose_name': 'изготовитель',
                'verbose_name_plural': 'изготовители',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание и характеристики')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('image', models.ImageField(blank=True, upload_to=main.models.phone_photo_path, verbose_name='Изображение')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выхода на продажу')),
                ('category', models.ManyToManyField(blank=True, to='main.category', verbose_name='Категория')),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.producer', verbose_name='изготовитель')),
            ],
            options={
                'verbose_name': 'телефон',
                'verbose_name_plural': 'телефоны',
            },
        ),
    ]
