# Generated by Django 5.1.4 on 2024-12-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='category',
            field=models.ManyToManyField(blank=True, to='main.category', verbose_name='Категории'),
        ),
        migrations.RemoveField(
            model_name='phone',
            name='producer',
        ),
        migrations.AddField(
            model_name='phone',
            name='producer',
            field=models.ManyToManyField(to='main.producer', verbose_name='Изготовители'),
        ),
    ]
